[package]
name = foodflow-audit
version = 0.1.0
description = FoodFlow AI - Solana Devnet Verifiable Notarization & Supply Chain Audit Program
edition = 2021

[lib]
crate-type = [cdylib, lib]
name = foodflow_audit

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = [no-entrypoint]
default = []

[dependencies]
anchor-lang = 0.29.0
solana-program = =1.17.0
sha2 = 0.10.8
borsh = 0.10.3
